// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SmartParking.Infrastructure.Data;

#nullable disable

namespace SmartParking.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526104930_AddUserAndZoneStatus")]
    partial class AddUserAndZoneStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SmartParking.Domain.Entities.Booking", b =>
                {
                    b.Property<int>("BookingID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("booking_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BookingID"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<int>("SpotID")
                        .HasColumnType("integer")
                        .HasColumnName("spot_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("UserID")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("VehicleID")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("BookingID")
                        .HasName("pk_bookings");

                    b.HasIndex("SpotID")
                        .HasDatabaseName("ix_bookings_spot_id");

                    b.HasIndex("UserID")
                        .HasDatabaseName("ix_bookings_user_id");

                    b.HasIndex("VehicleID")
                        .HasDatabaseName("ix_bookings_vehicle_id");

                    b.ToTable("bookings");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("notification_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("NotificationID"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("channel");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<int>("UserID")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("NotificationID")
                        .HasName("pk_notifications");

                    b.HasIndex("UserID")
                        .HasDatabaseName("ix_notifications_user_id");

                    b.ToTable("notifications");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.ParkingSession", b =>
                {
                    b.Property<int>("SessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SessionID"));

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<int>("SpotID")
                        .HasColumnType("integer")
                        .HasColumnName("spot_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("UserID")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("VehicleID")
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    b.HasKey("SessionID")
                        .HasName("pk_parking_sessions");

                    b.HasIndex("SpotID")
                        .HasDatabaseName("ix_parking_sessions_spot_id");

                    b.HasIndex("UserID")
                        .HasDatabaseName("ix_parking_sessions_user_id");

                    b.HasIndex("VehicleID")
                        .HasDatabaseName("ix_parking_sessions_vehicle_id");

                    b.ToTable("parking_sessions");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.ParkingSpot", b =>
                {
                    b.Property<int>("SpotID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("spot_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpotID"));

                    b.Property<string>("SpotNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("spot_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("ZoneID")
                        .HasColumnType("integer")
                        .HasColumnName("zone_id");

                    b.HasKey("SpotID")
                        .HasName("pk_parking_spots");

                    b.HasIndex("ZoneID")
                        .HasDatabaseName("ix_parking_spots_zone_id");

                    b.ToTable("parking_spots");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("payment_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentID"));

                    b.Property<double>("Amount")
                        .HasColumnType("double precision")
                        .HasColumnName("amount");

                    b.Property<int>("BookingID")
                        .HasColumnType("integer")
                        .HasColumnName("booking_id");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("method");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("PaymentID")
                        .HasName("pk_payments");

                    b.HasIndex("BookingID")
                        .IsUnique()
                        .HasDatabaseName("ix_payments_booking_id");

                    b.ToTable("payments");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("UserID")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("VehicleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("vehicle_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VehicleID"));

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("license_plate");

                    b.Property<int>("UserID")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("VehicleID")
                        .HasName("pk_vehicles");

                    b.HasIndex("LicensePlate")
                        .IsUnique()
                        .HasDatabaseName("ix_vehicles_license_plate");

                    b.HasIndex("UserID")
                        .HasDatabaseName("ix_vehicles_user_id");

                    b.ToTable("vehicles");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.Violation", b =>
                {
                    b.Property<int>("ViolationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("violation_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ViolationID"));

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<int?>("SessionID")
                        .HasColumnType("integer")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<int>("UserID")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("ViolationID")
                        .HasName("pk_violations");

                    b.HasIndex("SessionID")
                        .HasDatabaseName("ix_violations_session_id");

                    b.HasIndex("UserID")
                        .HasDatabaseName("ix_violations_user_id");

                    b.ToTable("violations");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.Zone", b =>
                {
                    b.Property<int>("ZoneID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("zone_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ZoneID"));

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_level");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("GeoJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("geo_json");

                    b.Property<int>("MaxDuration")
                        .HasColumnType("integer")
                        .HasColumnName("max_duration");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<double>("PricePerHour")
                        .HasColumnType("double precision")
                        .HasColumnName("price_per_hour");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("ZoneType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zone_type");

                    b.HasKey("ZoneID")
                        .HasName("pk_zones");

                    b.ToTable("zones");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.Booking", b =>
                {
                    b.HasOne("SmartParking.Domain.Entities.ParkingSpot", "Spot")
                        .WithMany("Bookings")
                        .HasForeignKey("SpotID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_parking_spots_spot_id");

                    b.HasOne("SmartParking.Domain.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_users_user_id");

                    b.HasOne("SmartParking.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Bookings")
                        .HasForeignKey("VehicleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bookings_vehicles_vehicle_id");

                    b.Navigation("Spot");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.Notification", b =>
                {
                    b.HasOne("SmartParking.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notifications_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.ParkingSession", b =>
                {
                    b.HasOne("SmartParking.Domain.Entities.ParkingSpot", "Spot")
                        .WithMany("Sessions")
                        .HasForeignKey("SpotID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parking_sessions_parking_spots_spot_id");

                    b.HasOne("SmartParking.Domain.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parking_sessions_users_user_id");

                    b.HasOne("SmartParking.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Sessions")
                        .HasForeignKey("VehicleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parking_sessions_vehicles_vehicle_id");

                    b.Navigation("Spot");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.ParkingSpot", b =>
                {
                    b.HasOne("SmartParking.Domain.Entities.Zone", "Zone")
                        .WithMany("Spots")
                        .HasForeignKey("ZoneID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_parking_spots_zones_zone_id");

                    b.Navigation("Zone");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.Payment", b =>
                {
                    b.HasOne("SmartParking.Domain.Entities.Booking", "Booking")
                        .WithOne("Payment")
                        .HasForeignKey("SmartParking.Domain.Entities.Payment", "BookingID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payments_bookings_booking_id");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("SmartParking.Domain.Entities.User", "User")
                        .WithMany("Vehicles")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vehicles_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.Violation", b =>
                {
                    b.HasOne("SmartParking.Domain.Entities.ParkingSession", "Session")
                        .WithMany("Violations")
                        .HasForeignKey("SessionID")
                        .HasConstraintName("fk_violations_parking_sessions_session_id");

                    b.HasOne("SmartParking.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_violations_users_user_id");

                    b.Navigation("Session");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.Booking", b =>
                {
                    b.Navigation("Payment");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.ParkingSession", b =>
                {
                    b.Navigation("Violations");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.ParkingSpot", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Notifications");

                    b.Navigation("Sessions");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("SmartParking.Domain.Entities.Zone", b =>
                {
                    b.Navigation("Spots");
                });
#pragma warning restore 612, 618
        }
    }
}
